use std::fmt::Write;

use serde::Serialize;
use ubtl_ir::{semantic_hash_hex, Effect, FnSignature, IR, IRType, Mutability, SourceVm, StorageSlot};

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GeneratedContract {
    pub contract_name: String,
    pub solidity: String,
    pub storage_map: StorageMap,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
pub struct StorageMap {
    pub contract: String,
    pub slots: Vec<StorageMapEntry>,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
pub struct StorageMapEntry {
    pub ir_id: String,
    pub evm_slot: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub offset: Option<u64>,
    pub ty: String,
}

#[derive(Clone, Debug)]
struct StructField {
    name: String,
    ty: String,
}

#[derive(Clone, Debug)]
struct StructDef {
    type_name: String,
    fields: Vec<StructField>,
    kind: StructKind,
}

#[derive(Clone, Debug, PartialEq, Eq)]
enum StructKind {
    Generic,
    Meta,
    LockEntry,
}

#[derive(Clone, Debug)]
enum SlotKind {
    Scalar,
    Tuple {
        struct_def: StructDef,
    },
    Map {
        key_type: String,
        value_type: String,
        value_struct: Option<StructDef>,
    },
}

#[derive(Clone, Debug)]
struct SlotModel {
    id: String,
    ir_type: IRType,
    var_name: String,
    declaration: String,
    kind: SlotKind,
}

#[derive(Clone, Debug, Default)]
struct AccessModel {
    price: Option<String>,
    remain: Option<String>,
    bridge: Option<String>,
    lock_size: Option<String>,
    locked_total: Option<String>,
    accounts_map: Option<String>,
    bookings_map: Option<String>,
    locks_map: Option<String>,
    lock_entry: Option<StructDef>,
}

pub fn emit(ir: &IR) -> Result<GeneratedContract, String> {
    let contract_name = translated_contract_name(&ir.meta.name);
    let slot_models = ir
        .storage
        .slots
        .iter()
        .map(build_slot_model)
        .collect::<Result<Vec<_>, _>>()?;
    let access = build_access_model(&slot_models);
    let ir_hash_hex = semantic_hash_hex(ir);

    let mut struct_defs = Vec::new();
    for slot in &slot_models {
        match &slot.kind {
            SlotKind::Tuple { struct_def } => push_struct_def(&mut struct_defs, struct_def.clone()),
            SlotKind::Map { value_struct, .. } => {
                if let Some(struct_def) = value_struct.clone() {
                    push_struct_def(&mut struct_defs, struct_def);
                }
            }
            SlotKind::Scalar => {}
        }
    }

    let mut solidity = String::new();
    writeln!(&mut solidity, "// SPDX-License-Identifier: MIT").unwrap();
    writeln!(&mut solidity, "pragma solidity ^0.8.28;").unwrap();
    writeln!(&mut solidity).unwrap();
    writeln!(&mut solidity, "// AUTO-GENERATED by UBTL Ψ_EVM; do not edit.").unwrap();
    writeln!(&mut solidity, "// Source IR hash: {ir_hash_hex}").unwrap();
    writeln!(
        &mut solidity,
        "// Source VM: {}",
        format_source_vm(&ir.meta.source_vm)
    )
    .unwrap();
    writeln!(&mut solidity, "contract {contract_name} {{").unwrap();
    writeln!(&mut solidity, "    error UbtlUnsupported(string reason);").unwrap();
    writeln!(
        &mut solidity,
        "    bytes32 public constant UBTL_IR_HASH = bytes32({ir_hash_hex});"
    )
    .unwrap();
    writeln!(&mut solidity).unwrap();

    for struct_def in &struct_defs {
        writeln!(&mut solidity, "    struct {} {{", struct_def.type_name).unwrap();
        for field in &struct_def.fields {
            writeln!(&mut solidity, "        {} {};", field.ty, field.name).unwrap();
        }
        writeln!(&mut solidity, "    }}").unwrap();
        writeln!(&mut solidity).unwrap();
    }

    for slot in &slot_models {
        writeln!(&mut solidity, "    {}", slot.declaration).unwrap();
    }
    if !slot_models.is_empty() {
        writeln!(&mut solidity).unwrap();
    }

    writeln!(&mut solidity, "    constructor() {{}}").unwrap();
    writeln!(&mut solidity).unwrap();
    let has_ir_hash_signature = ir
        .signatures
        .iter()
        .any(|signature| matches!(normalize_key(&signature.name).as_str(), "irhash" | "getirhash"));
    if !has_ir_hash_signature {
        writeln!(
            &mut solidity,
            "    function ir_hash() external pure returns (bytes32) {{"
        )
        .unwrap();
        writeln!(&mut solidity, "        return UBTL_IR_HASH;").unwrap();
        writeln!(&mut solidity, "    }}").unwrap();
    }

    if access.price.is_some() && access.remain.is_some() && access.locked_total.is_some() {
        writeln!(&mut solidity).unwrap();
        writeln!(
            &mut solidity,
            "    function __ubtl_available_units() internal view returns (uint256) {{"
        )
        .unwrap();
        let price = access.price.as_deref().unwrap_or("0");
        let remain = access.remain.as_deref().unwrap_or("0");
        let locked_total = access.locked_total.as_deref().unwrap_or("0");
        writeln!(&mut solidity, "        if ({price} == 0) {{").unwrap();
        writeln!(&mut solidity, "            return 0;").unwrap();
        writeln!(&mut solidity, "        }}").unwrap();
        writeln!(&mut solidity, "        uint256 lockedUnits = {locked_total} / {price};").unwrap();
        writeln!(
            &mut solidity,
            "        return {remain} > lockedUnits ? {remain} - lockedUnits : 0;"
        )
        .unwrap();
        writeln!(&mut solidity, "    }}").unwrap();
    }

    for signature in &ir.signatures {
        writeln!(&mut solidity).unwrap();
        emit_function(&mut solidity, signature, &access, &ir_hash_hex)?;
    }

    writeln!(&mut solidity).unwrap();
    emit_vassp_apply(&mut solidity, &ir.meta.name, &slot_models)?;
    writeln!(&mut solidity, "}}").unwrap();

    let storage_map = StorageMap {
        contract: contract_name.clone(),
        slots: slot_models
            .iter()
            .enumerate()
            .map(|(slot_index, slot)| StorageMapEntry {
                ir_id: slot.id.clone(),
                evm_slot: slot_index as u64,
                offset: None,
                ty: describe_ir_type(&slot.ir_type),
            })
            .collect(),
    };

    Ok(GeneratedContract {
        contract_name,
        solidity,
        storage_map,
    })
}

fn emit_function(
    out: &mut String,
    signature: &FnSignature,
    access: &AccessModel,
    ir_hash_hex: &str,
) -> Result<(), String> {
    let known_body = emit_known_function_body(signature, access, ir_hash_hex)?;
    let effective_mutability = if known_body.is_some() {
        solidity_mutability(&signature.mutability)
    } else {
        "pure"
    };
    let params = signature
        .inputs
        .iter()
        .enumerate()
        .map(|(index, ty)| {
            if known_body.is_some() {
                format!("{} arg{index}", solidity_param_type(ty))
            } else {
                solidity_param_type(ty)
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    let returns = if signature.outputs.is_empty() {
        String::new()
    } else {
        format!(
            " returns ({})",
            signature
                .outputs
                .iter()
                .map(solidity_return_type)
                .collect::<Vec<_>>()
                .join(", ")
        )
    };

    if effective_mutability.is_empty() {
        writeln!(
            out,
            "    function {}({}) external{} {{",
            signature.name, params, returns
        )
        .unwrap();
    } else {
        writeln!(
            out,
            "    function {}({}) external {}{} {{",
            signature.name, params, effective_mutability, returns
        )
        .unwrap();
    }

    if let Some(body) = known_body {
        for line in body.lines() {
            writeln!(out, "        {line}").unwrap();
        }
    } else {
        writeln!(
            out,
            "        revert UbtlUnsupported(\"function {} is outside the prototype subset\");",
            signature.name
        )
        .unwrap();
    }

    writeln!(out, "    }}").unwrap();
    Ok(())
}

fn emit_known_function_body(
    signature: &FnSignature,
    access: &AccessModel,
    ir_hash_hex: &str,
) -> Result<Option<String>, String> {
    let key = normalize_key(&signature.name);

    let body = match key.as_str() {
        "getprice" | "getticketprice" => access
            .price
            .as_ref()
            .map(|price| format!("return {price};")),
        "getremain" | "getseats" => access
            .remain
            .as_ref()
            .map(|remain| format!("return {remain};")),
        "getavailableremain" | "getavailableseats" => {
            if access.price.is_some() && access.remain.is_some() && access.locked_total.is_some() {
                Some("return __ubtl_available_units();".to_string())
            } else {
                None
            }
        }
        "getaccountbalance" => access
            .accounts_map
            .as_ref()
            .map(|map_name| format!("return {map_name}[arg0];")),
        "getbooking" | "getoutboundbooking" | "getreturnbooking" => access
            .bookings_map
            .as_ref()
            .map(|map_name| format!("return {map_name}[arg0];")),
        "isstatelocked" => {
            if let (Some(map_name), Some(lock_entry)) = (&access.locks_map, &access.lock_entry) {
                if lock_entry.kind == StructKind::LockEntry {
                    Some(format!("return {map_name}[arg0].active;"))
                } else {
                    None
                }
            } else {
                None
            }
        }
        "booklocal" => emit_book_local(access),
        "lockstate" => emit_lock_state(signature, access),
        "updatestate" => emit_update_state(access),
        "unlockstate" => emit_unlock_state(access, false),
        "unlockontimeout" => emit_unlock_state(access, true),
        "setbridge" => access
            .bridge
            .as_ref()
            .map(|bridge| format!("{bridge} = arg0;")),
        "getirhash" | "irhash" => Some(emit_ir_hash_return(signature, ir_hash_hex)?),
        _ => emit_effect_only_getter(signature, access),
    };

    Ok(body)
}

fn emit_ir_hash_return(signature: &FnSignature, ir_hash_hex: &str) -> Result<String, String> {
    if signature.outputs.len() != 1 {
        return Err(format!(
            "{} must have exactly one output to map to UBTL_IR_HASH",
            signature.name
        ));
    }

    let body = match &signature.outputs[0] {
        IRType::String => format!("return \"{ir_hash_hex}\";"),
        IRType::Bytes | IRType::Tuple(_) => "return abi.encodePacked(UBTL_IR_HASH);".to_string(),
        _ => "return UBTL_IR_HASH;".to_string(),
    };
    Ok(body)
}

fn emit_effect_only_getter(signature: &FnSignature, access: &AccessModel) -> Option<String> {
    if signature.outputs.len() != 1 || signature.effects.len() != 1 {
        return None;
    }

    let Effect::Read { slot } = &signature.effects[0] else {
        return None;
    };
    let slot_key = normalize_key(slot);

    if signature.inputs.is_empty() {
        if let Some(price) = &access.price {
            if slot_key.contains("price") {
                return Some(format!("return {price};"));
            }
        }
        if let Some(remain) = &access.remain {
            if slot_key.contains("remain") || slot_key.contains("seat") {
                return Some(format!("return {remain};"));
            }
        }
        if let Some(locked_total) = &access.locked_total {
            if slot_key.contains("lockedtotal") || slot_key.contains("locktotal") {
                return Some(format!("return {locked_total};"));
            }
        }
        return None;
    }

    if signature.inputs.len() == 1 {
        if slot_key.contains("account") {
            if let Some(accounts) = &access.accounts_map {
                return Some(format!("return {accounts}[arg0];"));
            }
        }
        if slot_key.contains("booking") {
            if let Some(bookings) = &access.bookings_map {
                return Some(format!("return {bookings}[arg0];"));
            }
        }
    }

    None
}

fn emit_book_local(access: &AccessModel) -> Option<String> {
    let price = access.price.as_deref()?;
    let remain = access.remain.as_deref()?;
    let accounts = access.accounts_map.as_deref()?;
    let bookings = access.bookings_map.as_deref()?;
    let mut body = String::new();
    writeln!(&mut body, "require(arg1 > 0, \"ZeroAmount\");").unwrap();
    if access.locked_total.is_some() {
        writeln!(
            &mut body,
            "require(__ubtl_available_units() >= arg1, \"InsufficientRemain\");"
        )
        .unwrap();
    } else {
        writeln!(&mut body, "require({remain} >= arg1, \"InsufficientRemain\");").unwrap();
    }
    writeln!(&mut body, "uint256 cost = {price} * arg1;").unwrap();
    writeln!(&mut body, "{remain} = {remain} > arg1 ? {remain} - arg1 : 0;").unwrap();
    writeln!(&mut body, "{accounts}[arg0] += cost;").unwrap();
    writeln!(&mut body, "{bookings}[arg0] += arg1;").unwrap();
    writeln!(&mut body, "return cost;").unwrap();
    Some(body.trim_end().to_string())
}

fn emit_lock_state(signature: &FnSignature, access: &AccessModel) -> Option<String> {
    if signature.inputs.len() < 3 {
        return None;
    }

    let price = access.price.as_deref()?;
    let remain = access.remain.as_deref()?;
    let lock_size = access.lock_size.as_deref().unwrap_or("1");
    let locked_total = access.locked_total.as_deref()?;
    let locks = access.locks_map.as_deref()?;
    let lock_entry = access.lock_entry.as_ref()?;
    if lock_entry.kind != StructKind::LockEntry {
        return None;
    }

    let mut body = String::new();
    writeln!(&mut body, "require(!{locks}[arg0].active, \"AlreadyLocked\");").unwrap();
    if access.locked_total.is_some() {
        writeln!(
            &mut body,
            "require(__ubtl_available_units() >= arg1, \"InsufficientRemain\");"
        )
        .unwrap();
    } else {
        writeln!(&mut body, "require({remain} >= arg1, \"InsufficientRemain\");").unwrap();
    }
    writeln!(
        &mut body,
        "uint256 amount = arg1 > 0 ? ({price} * arg1) : ({price} * {lock_size});"
    )
    .unwrap();
    writeln!(
        &mut body,
        "{locks}[arg0] = {}({{lockedAmount: amount, lockBlock: block.number, timeoutBlocks: arg2, active: true}});",
        lock_entry.type_name
    )
    .unwrap();
    writeln!(&mut body, "{locked_total} += amount;").unwrap();
    match signature.outputs.len() {
        0 => {}
        1 => {
            writeln!(&mut body, "return {price};").unwrap();
        }
        _ => {
            writeln!(&mut body, "return ({price}, {remain});").unwrap();
        }
    }
    Some(body.trim_end().to_string())
}

fn emit_update_state(access: &AccessModel) -> Option<String> {
    let remain = access.remain.as_deref()?;
    let accounts = access.accounts_map.as_deref()?;
    let bookings = access.bookings_map.as_deref()?;
    let locks = access.locks_map.as_deref()?;
    let locked_total = access.locked_total.as_deref()?;
    let mut body = String::new();
    writeln!(&mut body, "if ({locks}[arg0].active) {{").unwrap();
    writeln!(
        &mut body,
        "    {locked_total} = {locked_total} > {locks}[arg0].lockedAmount ? {locked_total} - {locks}[arg0].lockedAmount : 0;"
    )
    .unwrap();
    writeln!(&mut body, "    delete {locks}[arg0];").unwrap();
    writeln!(&mut body, "}}").unwrap();
    writeln!(&mut body, "{remain} = arg1;").unwrap();
    writeln!(&mut body, "{accounts}[arg2] += arg4;").unwrap();
    writeln!(&mut body, "{bookings}[arg2] += arg3;").unwrap();
    Some(body.trim_end().to_string())
}

fn emit_unlock_state(access: &AccessModel, with_timeout: bool) -> Option<String> {
    let locks = access.locks_map.as_deref()?;
    let locked_total = access.locked_total.as_deref()?;
    let mut body = String::new();
    writeln!(&mut body, "require({locks}[arg0].active, \"NotLocked\");").unwrap();
    if with_timeout {
        writeln!(
            &mut body,
            "require(block.number > {locks}[arg0].lockBlock + {locks}[arg0].timeoutBlocks, \"NotTimedOut\");"
        )
        .unwrap();
    }
    writeln!(
        &mut body,
        "{locked_total} = {locked_total} > {locks}[arg0].lockedAmount ? {locked_total} - {locks}[arg0].lockedAmount : 0;"
    )
    .unwrap();
    writeln!(&mut body, "delete {locks}[arg0];").unwrap();
    Some(body.trim_end().to_string())
}

fn emit_vassp_apply(
    out: &mut String,
    contract_name: &str,
    slot_models: &[SlotModel],
) -> Result<(), String> {
    writeln!(
        out,
        "    function __vassp_apply(bytes32 slot, bytes calldata value) external {{"
    )
    .unwrap();
    for slot in slot_models {
        match &slot.kind {
            SlotKind::Scalar => {
                let decode_ty = solidity_decode_type(&slot.ir_type);
                writeln!(
                    out,
                    "        if (slot == keccak256(abi.encodePacked(\"VASSP\", \"{}\", \"{}\"))) {{",
                    contract_name, slot.id
                )
                .unwrap();
                writeln!(
                    out,
                    "            {} = abi.decode(value, ({}));",
                    slot.var_name, decode_ty
                )
                .unwrap();
                writeln!(out, "            return;").unwrap();
                writeln!(out, "        }}").unwrap();
            }
            SlotKind::Tuple { struct_def } if struct_def.kind == StructKind::Meta => {
                writeln!(
                    out,
                    "        if (slot == keccak256(abi.encodePacked(\"VASSP\", \"{}\", \"{}\"))) {{",
                    contract_name, slot.id
                )
                .unwrap();
                writeln!(
                    out,
                    "            (string memory bridge_, uint256 price_, uint256 remain_, uint256 lockSize_) = abi.decode(value, (string, uint256, uint256, uint256));"
                )
                .unwrap();
                writeln!(
                    out,
                    "            {} = {}({{bridge: bridge_, price: price_, remain: remain_, lockSize: lockSize_}});",
                    slot.var_name, struct_def.type_name
                )
                .unwrap();
                writeln!(out, "            return;").unwrap();
                writeln!(out, "        }}").unwrap();
            }
            SlotKind::Tuple { .. } | SlotKind::Map { .. } => {}
        }
    }
    writeln!(
        out,
        "        revert UbtlUnsupported(\"__vassp_apply currently supports scalar and meta slots only\");"
    )
    .unwrap();
    writeln!(out, "    }}").unwrap();
    Ok(())
}

fn build_slot_model(slot: &StorageSlot) -> Result<SlotModel, String> {
    let var_name = canonical_slot_var_name(&slot.id);
    let kind = match &slot.ty {
        IRType::Map { key, val } => {
            let key_type = solidity_storage_type(key);
            let (value_type, value_struct) = match val.as_ref() {
                IRType::Tuple(items) => {
                    let struct_def = tuple_struct_for_slot(&slot.id, items)?;
                    (struct_def.type_name.clone(), Some(struct_def))
                }
                other => (solidity_storage_type(other), None),
            };

            SlotKind::Map {
                key_type,
                value_type,
                value_struct,
            }
        }
        IRType::Tuple(items) => SlotKind::Tuple {
            struct_def: tuple_struct_for_slot(&slot.id, items)?,
        },
        _ => SlotKind::Scalar,
    };

    let declaration = match &kind {
        SlotKind::Scalar => format!("{} private {};", solidity_storage_type(&slot.ty), var_name),
        SlotKind::Tuple { struct_def } => format!("{} private {};", struct_def.type_name, var_name),
        SlotKind::Map {
            key_type,
            value_type,
            ..
        } => format!("mapping({key_type} => {value_type}) private {var_name};"),
    };

    Ok(SlotModel {
        id: slot.id.clone(),
        ir_type: slot.ty.clone(),
        var_name,
        declaration,
        kind,
    })
}

fn build_access_model(slot_models: &[SlotModel]) -> AccessModel {
    let mut access = AccessModel::default();

    for slot in slot_models {
        let key = normalize_key(&slot.id);

        if let SlotKind::Tuple { struct_def } = &slot.kind {
            if struct_def.kind == StructKind::Meta {
                access.bridge = Some(format!("{}.bridge", slot.var_name));
                access.price = Some(format!("{}.price", slot.var_name));
                access.remain = Some(format!("{}.remain", slot.var_name));
                access.lock_size = Some(format!("{}.lockSize", slot.var_name));
            }
        }

        if let SlotKind::Map { value_struct, .. } = &slot.kind {
            if key.contains("account") {
                access.accounts_map = Some(slot.var_name.clone());
            }
            if key.contains("booking") {
                access.bookings_map = Some(slot.var_name.clone());
            }
            if key.contains("lock") && !key.contains("total") {
                access.locks_map = Some(slot.var_name.clone());
                access.lock_entry = value_struct.clone();
            }
        }

        if matches!(slot.kind, SlotKind::Scalar) {
            if key.contains("price") {
                access.price = Some(slot.var_name.clone());
            }
            if key.contains("remain") || key.contains("seat") {
                access.remain = Some(slot.var_name.clone());
            }
            if key.contains("bridge") {
                access.bridge = Some(slot.var_name.clone());
            }
            if key.contains("locksize") {
                access.lock_size = Some(slot.var_name.clone());
            }
            if key.contains("lockedtotal") || key.contains("locktotal") {
                access.locked_total = Some(slot.var_name.clone());
            }
        }
    }

    access
}

fn tuple_struct_for_slot(slot_id: &str, items: &[IRType]) -> Result<StructDef, String> {
    let normalized = normalize_key(slot_id);
    if normalized == "meta"
        && items.len() == 4
        && items[0] == IRType::String
        && matches!(items[1], IRType::U64 | IRType::U128 | IRType::U256 | IRType::U32)
        && matches!(items[2], IRType::U64 | IRType::U128 | IRType::U256 | IRType::U32)
        && matches!(items[3], IRType::U64 | IRType::U128 | IRType::U256 | IRType::U32)
    {
        return Ok(StructDef {
            type_name: "MetaSlot".to_string(),
            fields: vec![
                StructField {
                    name: "bridge".to_string(),
                    ty: "string".to_string(),
                },
                StructField {
                    name: "price".to_string(),
                    ty: "uint256".to_string(),
                },
                StructField {
                    name: "remain".to_string(),
                    ty: "uint256".to_string(),
                },
                StructField {
                    name: "lockSize".to_string(),
                    ty: "uint256".to_string(),
                },
            ],
            kind: StructKind::Meta,
        });
    }

    if normalized.contains("lock")
        && items.len() == 4
        && matches!(items[3], IRType::Bool)
    {
        return Ok(StructDef {
            type_name: "LockEntry".to_string(),
            fields: vec![
                StructField {
                    name: "lockedAmount".to_string(),
                    ty: "uint256".to_string(),
                },
                StructField {
                    name: "lockBlock".to_string(),
                    ty: "uint256".to_string(),
                },
                StructField {
                    name: "timeoutBlocks".to_string(),
                    ty: "uint256".to_string(),
                },
                StructField {
                    name: "active".to_string(),
                    ty: "bool".to_string(),
                },
            ],
            kind: StructKind::LockEntry,
        });
    }

    Ok(StructDef {
        type_name: format!("{}Slot", pascal_case(slot_id)),
        fields: items
            .iter()
            .enumerate()
            .map(|(index, item)| StructField {
                name: format!("field{index}"),
                ty: solidity_storage_type(item),
            })
            .collect(),
        kind: StructKind::Generic,
    })
}

fn push_struct_def(defs: &mut Vec<StructDef>, candidate: StructDef) {
    if defs.iter().any(|existing| existing.type_name == candidate.type_name) {
        return;
    }
    defs.push(candidate);
}

fn translated_contract_name(name: &str) -> String {
    if name.ends_with("Translated") {
        name.to_string()
    } else {
        format!("{}Translated", pascal_case(name))
    }
}

fn canonical_slot_var_name(slot_id: &str) -> String {
    let key = normalize_key(slot_id);
    if key == "meta" {
        return "meta".to_string();
    }
    if key.contains("account") {
        return "accounts".to_string();
    }
    if key.contains("booking") {
        return "bookings".to_string();
    }
    if key.contains("lockedtotal") || key.contains("locktotal") {
        return "lockedTotal".to_string();
    }
    if key.contains("locksize") {
        return "lockSize".to_string();
    }
    if key == "locks" || (key.contains("lock") && slot_id.contains('%')) {
        return "locks".to_string();
    }
    if key.contains("price") {
        return "price".to_string();
    }
    if key.contains("remain") || key.contains("seat") {
        return "remain".to_string();
    }
    if key.contains("bridge") {
        return "bridge".to_string();
    }
    camel_case(slot_id)
}

fn normalize_key(value: &str) -> String {
    value
        .chars()
        .filter(|ch| ch.is_ascii_alphanumeric())
        .flat_map(|ch| ch.to_lowercase())
        .collect()
}

fn camel_case(value: &str) -> String {
    let parts = split_words(value);
    if parts.is_empty() {
        return "slotValue".to_string();
    }

    let mut output = parts[0].clone();
    for part in parts.iter().skip(1) {
        output.push_str(&capitalize(part));
    }
    if is_solidity_keyword(&output) {
        format!("slot{}", capitalize(&output))
    } else {
        output
    }
}

fn pascal_case(value: &str) -> String {
    let parts = split_words(value);
    if parts.is_empty() {
        return "TranslatedContract".to_string();
    }

    parts.iter().map(|part| capitalize(part)).collect()
}

fn split_words(value: &str) -> Vec<String> {
    let mut words = Vec::new();
    let mut current = String::new();
    let mut previous_was_lower = false;

    for ch in value.chars() {
        if ch.is_ascii_uppercase() && previous_was_lower && !current.is_empty() {
            words.push(current.clone());
            current.clear();
        }

        if ch.is_ascii_alphanumeric() {
            current.push(ch.to_ascii_lowercase());
            previous_was_lower = ch.is_ascii_lowercase();
        } else if !current.is_empty() {
            words.push(current.clone());
            current.clear();
            previous_was_lower = false;
        } else {
            previous_was_lower = false;
        }
    }
    if !current.is_empty() {
        words.push(current);
    }

    words
}

fn capitalize(value: &str) -> String {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return String::new();
    };
    let mut output = String::new();
    output.push(first.to_ascii_uppercase());
    output.push_str(chars.as_str());
    output
}

fn solidity_storage_type(ty: &IRType) -> String {
    match ty {
        IRType::U256 | IRType::U128 | IRType::U64 | IRType::U32 => "uint256".to_string(),
        IRType::Bool => "bool".to_string(),
        IRType::Address => "address".to_string(),
        IRType::Bytes => "bytes".to_string(),
        IRType::String => "string".to_string(),
        IRType::Map { .. } => "bytes".to_string(),
        IRType::Tuple(_) => "bytes".to_string(),
    }
}

fn solidity_decode_type(ty: &IRType) -> String {
    match ty {
        IRType::Bytes => "bytes".to_string(),
        other => solidity_storage_type(other),
    }
}

fn solidity_param_type(ty: &IRType) -> String {
    match ty {
        IRType::Bytes => "bytes memory".to_string(),
        IRType::String => "string memory".to_string(),
        IRType::Map { .. } | IRType::Tuple(_) => "bytes memory".to_string(),
        other => solidity_storage_type(other),
    }
}

fn solidity_return_type(ty: &IRType) -> String {
    match ty {
        IRType::Bytes => "bytes memory".to_string(),
        IRType::String => "string memory".to_string(),
        IRType::Map { .. } | IRType::Tuple(_) => "bytes memory".to_string(),
        other => solidity_storage_type(other),
    }
}

fn solidity_mutability(mutability: &Mutability) -> &'static str {
    match mutability {
        Mutability::View => "view",
        Mutability::Pure => "pure",
        Mutability::NonPayable => "",
        Mutability::Payable => "payable",
    }
}

fn describe_ir_type(ty: &IRType) -> String {
    match ty {
        IRType::U256 => "U256".to_string(),
        IRType::U128 => "U128".to_string(),
        IRType::U64 => "U64".to_string(),
        IRType::U32 => "U32".to_string(),
        IRType::Bool => "Bool".to_string(),
        IRType::Address => "Address".to_string(),
        IRType::Bytes => "Bytes".to_string(),
        IRType::String => "String".to_string(),
        IRType::Map { key, val } => {
            format!("Map({}->{})", describe_ir_type(key), describe_ir_type(val))
        }
        IRType::Tuple(items) => format!(
            "Tuple({})",
            items
                .iter()
                .map(describe_ir_type)
                .collect::<Vec<_>>()
                .join(",")
        ),
    }
}

fn format_source_vm(vm: &SourceVm) -> String {
    match vm {
        SourceVm::Evm { solc_version } => format!("Evm({solc_version})"),
        SourceVm::Wasm { ink_version } => format!("Wasm({ink_version})"),
        SourceVm::Fabric { go_version } => format!("Fabric({go_version})"),
        SourceVm::Any => "Any".to_string(),
    }
}

fn is_solidity_keyword(value: &str) -> bool {
    matches!(
        value,
        "address"
            | "string"
            | "bytes"
            | "contract"
            | "mapping"
            | "function"
            | "event"
            | "error"
            | "return"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use ubtl_ir::{
        BasicBlock, ContractMeta, ControlFlowGraph, FnSignature, IR, Mutability, NativeEncoding,
        StorageLayout, StorageSlot, Terminator,
    };

    fn placeholder_cfg(block_count: usize) -> ControlFlowGraph {
        let blocks = (0..block_count)
            .map(|id| BasicBlock {
                id: id as u32,
                preds: Vec::new(),
                ops: Vec::new(),
                term: Terminator::Return(Vec::new()),
            })
            .collect();
        ControlFlowGraph { blocks }
    }

    #[test]
    fn emits_wasm_style_train_contract() {
        let ir = IR {
            meta: ContractMeta {
                name: "TrainBooking".to_string(),
                version: "ink5".to_string(),
                source_vm: SourceVm::Wasm {
                    ink_version: "5.0.0".to_string(),
                },
                source_hash: [1u8; 32],
            },
            storage: StorageLayout {
                slots: vec![
                    StorageSlot {
                        id: "bridge".to_string(),
                        ty: IRType::Address,
                        native_offset: 0,
                        native_encoding: NativeEncoding::WasmMap {
                            hash: "Blake2b_128".to_string(),
                        },
                    },
                    StorageSlot {
                        id: "price".to_string(),
                        ty: IRType::U128,
                        native_offset: 1,
                        native_encoding: NativeEncoding::WasmMap {
                            hash: "Blake2b_128".to_string(),
                        },
                    },
                    StorageSlot {
                        id: "remain".to_string(),
                        ty: IRType::U64,
                        native_offset: 2,
                        native_encoding: NativeEncoding::WasmMap {
                            hash: "Blake2b_128".to_string(),
                        },
                    },
                    StorageSlot {
                        id: "locks".to_string(),
                        ty: IRType::Map {
                            key: Box::new(IRType::U64),
                            val: Box::new(IRType::Tuple(vec![
                                IRType::U128,
                                IRType::U32,
                                IRType::U32,
                                IRType::Bool,
                            ])),
                        },
                        native_offset: 3,
                        native_encoding: NativeEncoding::WasmMap {
                            hash: "Blake2b_128".to_string(),
                        },
                    },
                    StorageSlot {
                        id: "locked_total".to_string(),
                        ty: IRType::U128,
                        native_offset: 4,
                        native_encoding: NativeEncoding::WasmMap {
                            hash: "Blake2b_128".to_string(),
                        },
                    },
                    StorageSlot {
                        id: "accounts".to_string(),
                        ty: IRType::Map {
                            key: Box::new(IRType::Address),
                            val: Box::new(IRType::U128),
                        },
                        native_offset: 5,
                        native_encoding: NativeEncoding::WasmMap {
                            hash: "Blake2b_128".to_string(),
                        },
                    },
                    StorageSlot {
                        id: "bookings".to_string(),
                        ty: IRType::Map {
                            key: Box::new(IRType::Address),
                            val: Box::new(IRType::U64),
                        },
                        native_offset: 6,
                        native_encoding: NativeEncoding::WasmMap {
                            hash: "Blake2b_128".to_string(),
                        },
                    },
                    StorageSlot {
                        id: "lock_size".to_string(),
                        ty: IRType::U64,
                        native_offset: 7,
                        native_encoding: NativeEncoding::WasmMap {
                            hash: "Blake2b_128".to_string(),
                        },
                    },
                ],
            },
            signatures: vec![
                FnSignature {
                    name: "get_price".to_string(),
                    selector4: [0u8; 4],
                    inputs: vec![],
                    outputs: vec![IRType::U128],
                    mutability: Mutability::View,
                    effects: vec![Effect::Read {
                        slot: "price".to_string(),
                    }],
                    entry_block: 0,
                },
                FnSignature {
                    name: "get_available_remain".to_string(),
                    selector4: [1u8; 4],
                    inputs: vec![],
                    outputs: vec![IRType::U64],
                    mutability: Mutability::View,
                    effects: vec![
                        Effect::Read {
                            slot: "price".to_string(),
                        },
                        Effect::Read {
                            slot: "remain".to_string(),
                        },
                        Effect::Read {
                            slot: "locked_total".to_string(),
                        },
                    ],
                    entry_block: 1,
                },
                FnSignature {
                    name: "get_account_balance".to_string(),
                    selector4: [2u8; 4],
                    inputs: vec![IRType::Address],
                    outputs: vec![IRType::U128],
                    mutability: Mutability::View,
                    effects: vec![Effect::Read {
                        slot: "accounts".to_string(),
                    }],
                    entry_block: 2,
                },
                FnSignature {
                    name: "book_local".to_string(),
                    selector4: [3u8; 4],
                    inputs: vec![IRType::Address, IRType::U64],
                    outputs: vec![IRType::U128],
                    mutability: Mutability::NonPayable,
                    effects: vec![
                        Effect::Read {
                            slot: "price".to_string(),
                        },
                        Effect::Write {
                            slot: "remain".to_string(),
                        },
                    ],
                    entry_block: 3,
                },
                FnSignature {
                    name: "lock_state".to_string(),
                    selector4: [4u8; 4],
                    inputs: vec![IRType::U64, IRType::U64, IRType::U32],
                    outputs: vec![IRType::U128, IRType::U64],
                    mutability: Mutability::NonPayable,
                    effects: vec![
                        Effect::Read {
                            slot: "price".to_string(),
                        },
                        Effect::Write {
                            slot: "locks".to_string(),
                        },
                    ],
                    entry_block: 4,
                },
            ],
            cfg: placeholder_cfg(5),
            externals: Vec::new(),
        };

        let generated = emit(&ir).expect("backend emit should succeed");
        assert_eq!(generated.contract_name, "TrainBookingTranslated");
        assert!(generated.solidity.contains("contract TrainBookingTranslated"));
        assert!(generated.solidity.contains("struct LockEntry"));
        assert!(generated.solidity.contains("mapping(address => uint256) private accounts;"));
        assert!(generated.solidity.contains("function get_price() external view returns (uint256)"));
        assert!(generated.solidity.contains("function book_local(address arg0, uint256 arg1) external returns (uint256)"));
        assert!(generated.solidity.contains("function __vassp_apply(bytes32 slot, bytes calldata value) external"));
        assert_eq!(generated.storage_map.slots.len(), 8);
    }

    #[test]
    fn emits_fabric_meta_tuple_contract() {
        let ir = IR {
            meta: ContractMeta {
                name: "HotelBooking".to_string(),
                version: "go1.21".to_string(),
                source_vm: SourceVm::Fabric {
                    go_version: "1.21".to_string(),
                },
                source_hash: [2u8; 32],
            },
            storage: StorageLayout {
                slots: vec![
                    StorageSlot {
                        id: "META".to_string(),
                        ty: IRType::Tuple(vec![
                            IRType::String,
                            IRType::U64,
                            IRType::U64,
                            IRType::U64,
                        ]),
                        native_offset: 0,
                        native_encoding: NativeEncoding::FabricKey {
                            pattern: "META".to_string(),
                        },
                    },
                    StorageSlot {
                        id: "ACCOUNT_%s".to_string(),
                        ty: IRType::Map {
                            key: Box::new(IRType::String),
                            val: Box::new(IRType::U64),
                        },
                        native_offset: 1,
                        native_encoding: NativeEncoding::FabricKey {
                            pattern: "ACCOUNT_%s".to_string(),
                        },
                    },
                    StorageSlot {
                        id: "BOOKING_%s".to_string(),
                        ty: IRType::Map {
                            key: Box::new(IRType::String),
                            val: Box::new(IRType::U64),
                        },
                        native_offset: 2,
                        native_encoding: NativeEncoding::FabricKey {
                            pattern: "BOOKING_%s".to_string(),
                        },
                    },
                    StorageSlot {
                        id: "LOCK_%s".to_string(),
                        ty: IRType::Map {
                            key: Box::new(IRType::String),
                            val: Box::new(IRType::Tuple(vec![
                                IRType::U64,
                                IRType::U64,
                                IRType::U64,
                                IRType::Bool,
                            ])),
                        },
                        native_offset: 3,
                        native_encoding: NativeEncoding::FabricKey {
                            pattern: "LOCK_%s".to_string(),
                        },
                    },
                    StorageSlot {
                        id: "LOCK_TOTAL".to_string(),
                        ty: IRType::U64,
                        native_offset: 4,
                        native_encoding: NativeEncoding::FabricKey {
                            pattern: "LOCK_TOTAL".to_string(),
                        },
                    },
                ],
            },
            signatures: vec![
                FnSignature {
                    name: "GetPrice".to_string(),
                    selector4: [0u8; 4],
                    inputs: vec![],
                    outputs: vec![IRType::U64],
                    mutability: Mutability::View,
                    effects: vec![Effect::Read {
                        slot: "META".to_string(),
                    }],
                    entry_block: 0,
                },
                FnSignature {
                    name: "LockState".to_string(),
                    selector4: [1u8; 4],
                    inputs: vec![IRType::String, IRType::U64, IRType::U64],
                    outputs: vec![IRType::U64, IRType::U64],
                    mutability: Mutability::NonPayable,
                    effects: vec![
                        Effect::Read {
                            slot: "META".to_string(),
                        },
                        Effect::Write {
                            slot: "LOCK_%s".to_string(),
                        },
                    ],
                    entry_block: 1,
                },
            ],
            cfg: placeholder_cfg(2),
            externals: Vec::new(),
        };

        let generated = emit(&ir).expect("fabric emit should succeed");
        assert!(generated.solidity.contains("struct MetaSlot"));
        assert!(generated.solidity.contains("MetaSlot private meta;"));
        assert!(generated.solidity.contains("mapping(string => uint256) private accounts;"));
        assert!(generated.solidity.contains("return meta.price;"));
        assert!(generated.solidity.contains("function LockState(string memory arg0, uint256 arg1, uint256 arg2) external returns (uint256, uint256)"));
        assert!(generated.solidity.contains("meta = MetaSlot({bridge: bridge_, price: price_, remain: remain_, lockSize: lockSize_});"));
    }
}
