package event

var xsmartABI = mustABI(`[
  {"anonymous":false,"inputs":[{"indexed":false,"internalType":"string","name":"serviceId","type":"string"},{"indexed":false,"internalType":"uint256","name":"invokedChainId","type":"uint256"},{"indexed":false,"internalType":"address[]","name":"logicContractAddresses","type":"address[]"}],"name":"DeployRequestEmitted","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":false,"internalType":"string","name":"serviceId","type":"string"},{"indexed":false,"internalType":"address","name":"logicContract","type":"address"},{"indexed":false,"internalType":"uint256","name":"chainId","type":"uint256"}],"name":"LogicContractRegistered","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":false,"internalType":"address","name":"stateContract","type":"address"},{"indexed":false,"internalType":"uint256","name":"chainId","type":"uint256"}],"name":"StateContractRegistered","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":false,"internalType":"string","name":"serviceId","type":"string"},{"indexed":false,"internalType":"bytes32","name":"bytecodeHash","type":"bytes32"},{"indexed":false,"internalType":"uint256","name":"targetChainId","type":"uint256"}],"name":"VerificationRequested","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":false,"internalType":"string","name":"serviceId","type":"string"},{"indexed":false,"internalType":"bool","name":"success","type":"bool"}],"name":"VerificationResult","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"crossChainTxId","type":"uint256"},{"indexed":false,"internalType":"string","name":"serviceId","type":"string"},{"indexed":false,"internalType":"address[]","name":"stateContracts","type":"address[]"},{"indexed":false,"internalType":"uint256","name":"executionChainId","type":"uint256"}],"name":"CrossChainLockRequested","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"crossChainTxId","type":"uint256"},{"indexed":false,"internalType":"address","name":"stateContract","type":"address"},{"indexed":false,"internalType":"bytes","name":"lockedState","type":"bytes"}],"name":"CrossChainLockResponse","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"crossChainTxId","type":"uint256"},{"indexed":false,"internalType":"address[]","name":"stateContracts","type":"address[]"},{"indexed":false,"internalType":"bytes[]","name":"updateData","type":"bytes[]"}],"name":"CrossChainUpdateRequested","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"crossChainTxId","type":"uint256"},{"indexed":false,"internalType":"address","name":"stateContract","type":"address"},{"indexed":false,"internalType":"bool","name":"success","type":"bool"}],"name":"CrossChainUpdateAck","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"crossChainTxId","type":"uint256"},{"indexed":false,"internalType":"address[]","name":"stateContracts","type":"address[]"}],"name":"CrossChainRollback","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"crossChainTxId","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"fee","type":"uint256"}],"name":"CrossChainFeePaid","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"target","type":"address"},{"indexed":true,"internalType":"uint256","name":"crossChainTxId","type":"uint256"}],"name":"UnlockFailed","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"target","type":"address"},{"indexed":true,"internalType":"uint256","name":"crossChainTxId","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"attempt","type":"uint256"}],"name":"UnlockRetryRequested","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"target","type":"address"},{"indexed":true,"internalType":"uint256","name":"crossChainTxId","type":"uint256"}],"name":"UnlockForcedTimeout","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"crossChainTxId","type":"uint256"},{"indexed":false,"internalType":"string","name":"serviceId","type":"string"},{"indexed":false,"internalType":"address","name":"logicContract","type":"address"},{"indexed":false,"internalType":"bytes","name":"resultHash","type":"bytes"}],"name":"IntegratedExecutionPerformed","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"crossChainTxId","type":"uint256"},{"indexed":false,"internalType":"string","name":"serviceId","type":"string"},{"indexed":false,"internalType":"bytes","name":"reason","type":"bytes"}],"name":"IntegratedExecutionFailed","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"crossChainTxId","type":"uint256"},{"indexed":true,"internalType":"bytes32","name":"translationKey","type":"bytes32"},{"indexed":false,"internalType":"bytes32","name":"peerIrHash","type":"bytes32"}],"name":"TranslationVerificationFailed","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"crossChainTxId","type":"uint256"},{"indexed":true,"internalType":"uint256","name":"nodeIndex","type":"uint256"},{"indexed":true,"internalType":"address","name":"contractAddr","type":"address"},{"indexed":false,"internalType":"bytes","name":"result","type":"bytes"}],"name":"CallTreeNodeExecuted","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"crossChainTxId","type":"uint256"},{"indexed":true,"internalType":"address","name":"completedBy","type":"address"}],"name":"ExecutionCompleted","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"key","type":"bytes32"},{"indexed":true,"internalType":"uint256","name":"sourceChainId","type":"uint256"},{"indexed":true,"internalType":"bytes32","name":"sourceContractHash","type":"bytes32"},{"indexed":false,"internalType":"bytes32","name":"irHash","type":"bytes32"},{"indexed":false,"internalType":"address","name":"translated","type":"address"},{"indexed":false,"internalType":"bytes32","name":"storageMapRoot","type":"bytes32"},{"indexed":false,"internalType":"address","name":"dAppProvider","type":"address"},{"indexed":false,"internalType":"uint256","name":"registeredAt","type":"uint256"}],"name":"TranslationRegistered","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"key","type":"bytes32"},{"indexed":false,"internalType":"bool","name":"ok","type":"bool"}],"name":"TranslationVerified","type":"event"}
]`)
