package event

var gpactABI = mustABI(`[
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"crosschainTxId","type":"bytes32"},{"indexed":true,"internalType":"address","name":"user","type":"address"},{"indexed":false,"internalType":"uint256","name":"rooms","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"outbound","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"returnTickets","type":"uint256"}],"name":"BookingStarted","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"crosschainTxId","type":"bytes32"},{"indexed":true,"internalType":"uint256","name":"rootChainId","type":"uint256"},{"indexed":false,"internalType":"bytes32","name":"callTreeHash","type":"bytes32"},{"indexed":false,"internalType":"uint256","name":"timeoutBlock","type":"uint256"}],"name":"StartEvent","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"crosschainTxId","type":"bytes32"},{"indexed":false,"internalType":"uint256","name":"startBlock","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"timeoutBlock","type":"uint256"}],"name":"RootTimedOut","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"crosschainTxId","type":"bytes32"},{"indexed":true,"internalType":"uint256","name":"chainId","type":"uint256"},{"indexed":true,"internalType":"uint256","name":"segmentId","type":"uint256"},{"indexed":false,"internalType":"bytes32","name":"callTreeHash","type":"bytes32"},{"indexed":false,"internalType":"bool","name":"success","type":"bool"},{"indexed":false,"internalType":"bool","name":"locked","type":"bool"},{"indexed":false,"internalType":"bytes","name":"result","type":"bytes"}],"name":"SegmentEvent","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"crosschainTxId","type":"bytes32"},{"indexed":true,"internalType":"uint256","name":"rootChainId","type":"uint256"},{"indexed":false,"internalType":"bytes32","name":"callTreeHash","type":"bytes32"},{"indexed":false,"internalType":"bool","name":"commit","type":"bool"},{"indexed":false,"internalType":"bool","name":"abortTx","type":"bool"}],"name":"RootEvent","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"crosschainTxId","type":"bytes32"},{"indexed":true,"internalType":"uint256","name":"chainId","type":"uint256"},{"indexed":true,"internalType":"uint256","name":"segmentId","type":"uint256"},{"indexed":false,"internalType":"bool","name":"commit","type":"bool"}],"name":"SignallingEvent","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"crosschainTxId","type":"bytes32"}],"name":"LockTimedOut","type":"event"}
]`)
