package event

var atomABI = mustABI(`[
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"},{"indexed":true,"internalType":"address","name":"user","type":"address"},{"indexed":false,"internalType":"uint256","name":"numRooms","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"numOutboundTickets","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"numReturnTickets","type":"uint256"}],"name":"WriteOnlyInvocationRequested","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"},{"indexed":true,"internalType":"address","name":"user","type":"address"},{"indexed":false,"internalType":"uint256","name":"numRooms","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"numOutboundTickets","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"numReturnTickets","type":"uint256"}],"name":"ReadWriteInvocationRequested","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"},{"indexed":false,"internalType":"address[]","name":"judges","type":"address[]"}],"name":"JudgesSelected","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"},{"indexed":true,"internalType":"bytes32","name":"workflowId","type":"bytes32"},{"indexed":true,"internalType":"address","name":"server","type":"address"},{"indexed":false,"internalType":"address","name":"entry","type":"address"},{"indexed":false,"internalType":"uint256","name":"totalOperationCount","type":"uint256"}],"name":"InvocationStarted","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"},{"indexed":true,"internalType":"uint256","name":"operationId","type":"uint256"},{"indexed":true,"internalType":"uint256","name":"chainId","type":"uint256"},{"indexed":false,"internalType":"bytes32","name":"lockDoTxHash","type":"bytes32"},{"indexed":false,"internalType":"bytes32","name":"unlockTxHash","type":"bytes32"},{"indexed":false,"internalType":"bytes32","name":"undoTxHash","type":"bytes32"},{"indexed":false,"internalType":"bytes32","name":"readTxHash","type":"bytes32"},{"indexed":false,"internalType":"bytes32","name":"dependencyHash","type":"bytes32"},{"indexed":false,"internalType":"bytes32","name":"proofHash","type":"bytes32"}],"name":"OperationProofSubmitted","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"},{"indexed":false,"internalType":"uint256","name":"proofCount","type":"uint256"}],"name":"AllProofsSubmitted","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"},{"indexed":true,"internalType":"address","name":"judge","type":"address"},{"indexed":false,"internalType":"bool","name":"valid","type":"bool"},{"indexed":false,"internalType":"bytes32","name":"auditHash","type":"bytes32"}],"name":"JudgeVoteSubmitted","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"}],"name":"InvocationFinalized","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"}],"name":"InvocationInvalidated","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"},{"indexed":false,"internalType":"uint256","name":"newServiceDeadlineBlock","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"newAuditDeadlineBlock","type":"uint256"}],"name":"InvocationExtended","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"}],"name":"InvocationForceSettled","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"},{"indexed":true,"internalType":"address","name":"server","type":"address"},{"indexed":false,"internalType":"uint256","name":"totalOperationCount","type":"uint256"}],"name":"ForceSettleUndoRequired","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"},{"indexed":true,"internalType":"address","name":"user","type":"address"},{"indexed":false,"internalType":"uint256","name":"rooms","type":"uint256"},{"indexed":false,"internalType":"bytes32","name":"lockHash","type":"bytes32"}],"name":"AtomHotelLocked","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"},{"indexed":true,"internalType":"address","name":"user","type":"address"},{"indexed":false,"internalType":"uint256","name":"rooms","type":"uint256"}],"name":"AtomHotelUnlocked","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"},{"indexed":true,"internalType":"address","name":"user","type":"address"},{"indexed":false,"internalType":"uint256","name":"rooms","type":"uint256"}],"name":"AtomHotelUndoUnlocked","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"},{"indexed":true,"internalType":"address","name":"user","type":"address"},{"indexed":false,"internalType":"uint256","name":"outboundTickets","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"returnTickets","type":"uint256"},{"indexed":false,"internalType":"bytes32","name":"lockHash","type":"bytes32"}],"name":"AtomTrainLocked","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"},{"indexed":true,"internalType":"address","name":"user","type":"address"},{"indexed":false,"internalType":"uint256","name":"outboundTickets","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"returnTickets","type":"uint256"}],"name":"AtomTrainUnlocked","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"},{"indexed":true,"internalType":"address","name":"user","type":"address"},{"indexed":false,"internalType":"uint256","name":"outboundTickets","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"returnTickets","type":"uint256"}],"name":"AtomTrainUndoUnlocked","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"},{"indexed":true,"internalType":"address","name":"user","type":"address"},{"indexed":false,"internalType":"uint256","name":"seats","type":"uint256"},{"indexed":false,"internalType":"bytes32","name":"lockHash","type":"bytes32"}],"name":"AtomFlightLocked","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"},{"indexed":true,"internalType":"address","name":"user","type":"address"},{"indexed":false,"internalType":"uint256","name":"seats","type":"uint256"}],"name":"AtomFlightUnlocked","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"},{"indexed":true,"internalType":"address","name":"user","type":"address"},{"indexed":false,"internalType":"uint256","name":"seats","type":"uint256"}],"name":"AtomFlightUndoUnlocked","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"},{"indexed":true,"internalType":"address","name":"user","type":"address"},{"indexed":false,"internalType":"uint256","name":"cars","type":"uint256"},{"indexed":false,"internalType":"bytes32","name":"lockHash","type":"bytes32"}],"name":"AtomTaxiLocked","type":"event"}
  ,{"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"},{"indexed":true,"internalType":"address","name":"user","type":"address"},{"indexed":false,"internalType":"uint256","name":"cars","type":"uint256"}],"name":"AtomTaxiUnlocked","type":"event"}
  ,{"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"invokeId","type":"bytes32"},{"indexed":true,"internalType":"address","name":"user","type":"address"},{"indexed":false,"internalType":"uint256","name":"cars","type":"uint256"}],"name":"AtomTaxiUndoUnlocked","type":"event"}
]`)
